apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
spec:
  type: {{ .Values.service.type }}
  selector:
    # Must match the dynamic label we set in the Deployment's template
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      # The external port the Service exposes to the world (from values.yaml)
      port: {{ .Values.service.port }}
      # The internal port inside the container where our Flask app actually listens
      targetPort: 8080