apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Name of the application inside ArgoCD
  name: url-shortener
  namespace: argocd
spec:
  # Logical project grouping inside ArgoCD
  project: default
  source:
    # Target GitHub repository
    repoURL: 'https://github.com/noa020604/sailpoint-homelab.git'
    # Git branch to watch for changes
    targetRevision: main
    # Path to the Helm chart folder in the repo
    path: url-shortener-chart
  destination:
    # Deploys to the local Kubernetes cluster
    server: 'https://kubernetes.default.svc'
    # Target namespace for the application workloads
    namespace: url-shortener
  syncPolicy:
    automated:
      # Automatically apply changes from Git to the cluster
      prune: true
      # Automatically overwrites manual cluster changes to match Git state
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
